In [4]:
import torch
import torch.nn as nn
from transformers import GPT2Model, GPT2Config
from tqdm import tqdm
from sklearn.svm import LinearSVC
from sklearn.linear_model import LogisticRegression, Lasso
import warnings
from sklearn import tree
import xgboost as xgb

from base_models import NeuralNetwork, ParallelNetworks


In [20]:
from transformers import GPT2LMHeadModel, AutoConfig

In [23]:
from models import TransformerModel

In [27]:
model = TransformerModel(20, 101)

In [29]:
config = GPT2Config(
            n_positions=2 * 101,
            n_embd=256,
            n_layer=12,
            n_head=8,
            resid_pdrop=0.0,
            embd_pdrop=0.0,
            attn_pdrop=0.0,
            use_cache=False,
        )

In [38]:
config = GPT2Config.from_pretrained("gpt2")  # Assuming the model was trained using the GPT-2 base configuration
model = GPT2Model(config)
model.load_state_dict(model_state_dict["model_state_dict"])

RuntimeError: Error(s) in loading state_dict for GPT2Model:
	Missing key(s) in state_dict: "wte.weight", "wpe.weight", "h.0.ln_1.weight", "h.0.ln_1.bias", "h.0.attn.bias", "h.0.attn.masked_bias", "h.0.attn.c_attn.weight", "h.0.attn.c_attn.bias", "h.0.attn.c_proj.weight", "h.0.attn.c_proj.bias", "h.0.ln_2.weight", "h.0.ln_2.bias", "h.0.mlp.c_fc.weight", "h.0.mlp.c_fc.bias", "h.0.mlp.c_proj.weight", "h.0.mlp.c_proj.bias", "h.1.ln_1.weight", "h.1.ln_1.bias", "h.1.attn.bias", "h.1.attn.masked_bias", "h.1.attn.c_attn.weight", "h.1.attn.c_attn.bias", "h.1.attn.c_proj.weight", "h.1.attn.c_proj.bias", "h.1.ln_2.weight", "h.1.ln_2.bias", "h.1.mlp.c_fc.weight", "h.1.mlp.c_fc.bias", "h.1.mlp.c_proj.weight", "h.1.mlp.c_proj.bias", "h.2.ln_1.weight", "h.2.ln_1.bias", "h.2.attn.bias", "h.2.attn.masked_bias", "h.2.attn.c_attn.weight", "h.2.attn.c_attn.bias", "h.2.attn.c_proj.weight", "h.2.attn.c_proj.bias", "h.2.ln_2.weight", "h.2.ln_2.bias", "h.2.mlp.c_fc.weight", "h.2.mlp.c_fc.bias", "h.2.mlp.c_proj.weight", "h.2.mlp.c_proj.bias", "h.3.ln_1.weight", "h.3.ln_1.bias", "h.3.attn.bias", "h.3.attn.masked_bias", "h.3.attn.c_attn.weight", "h.3.attn.c_attn.bias", "h.3.attn.c_proj.weight", "h.3.attn.c_proj.bias", "h.3.ln_2.weight", "h.3.ln_2.bias", "h.3.mlp.c_fc.weight", "h.3.mlp.c_fc.bias", "h.3.mlp.c_proj.weight", "h.3.mlp.c_proj.bias", "h.4.ln_1.weight", "h.4.ln_1.bias", "h.4.attn.bias", "h.4.attn.masked_bias", "h.4.attn.c_attn.weight", "h.4.attn.c_attn.bias", "h.4.attn.c_proj.weight", "h.4.attn.c_proj.bias", "h.4.ln_2.weight", "h.4.ln_2.bias", "h.4.mlp.c_fc.weight", "h.4.mlp.c_fc.bias", "h.4.mlp.c_proj.weight", "h.4.mlp.c_proj.bias", "h.5.ln_1.weight", "h.5.ln_1.bias", "h.5.attn.bias", "h.5.attn.masked_bias", "h.5.attn.c_attn.weight", "h.5.attn.c_attn.bias", "h.5.attn.c_proj.weight", "h.5.attn.c_proj.bias", "h.5.ln_2.weight", "h.5.ln_2.bias", "h.5.mlp.c_fc.weight", "h.5.mlp.c_fc.bias", "h.5.mlp.c_proj.weight", "h.5.mlp.c_proj.bias", "h.6.ln_1.weight", "h.6.ln_1.bias", "h.6.attn.bias", "h.6.attn.masked_bias", "h.6.attn.c_attn.weight", "h.6.attn.c_attn.bias", "h.6.attn.c_proj.weight", "h.6.attn.c_proj.bias", "h.6.ln_2.weight", "h.6.ln_2.bias", "h.6.mlp.c_fc.weight", "h.6.mlp.c_fc.bias", "h.6.mlp.c_proj.weight", "h.6.mlp.c_proj.bias", "h.7.ln_1.weight", "h.7.ln_1.bias", "h.7.attn.bias", "h.7.attn.masked_bias", "h.7.attn.c_attn.weight", "h.7.attn.c_attn.bias", "h.7.attn.c_proj.weight", "h.7.attn.c_proj.bias", "h.7.ln_2.weight", "h.7.ln_2.bias", "h.7.mlp.c_fc.weight", "h.7.mlp.c_fc.bias", "h.7.mlp.c_proj.weight", "h.7.mlp.c_proj.bias", "h.8.ln_1.weight", "h.8.ln_1.bias", "h.8.attn.bias", "h.8.attn.masked_bias", "h.8.attn.c_attn.weight", "h.8.attn.c_attn.bias", "h.8.attn.c_proj.weight", "h.8.attn.c_proj.bias", "h.8.ln_2.weight", "h.8.ln_2.bias", "h.8.mlp.c_fc.weight", "h.8.mlp.c_fc.bias", "h.8.mlp.c_proj.weight", "h.8.mlp.c_proj.bias", "h.9.ln_1.weight", "h.9.ln_1.bias", "h.9.attn.bias", "h.9.attn.masked_bias", "h.9.attn.c_attn.weight", "h.9.attn.c_attn.bias", "h.9.attn.c_proj.weight", "h.9.attn.c_proj.bias", "h.9.ln_2.weight", "h.9.ln_2.bias", "h.9.mlp.c_fc.weight", "h.9.mlp.c_fc.bias", "h.9.mlp.c_proj.weight", "h.9.mlp.c_proj.bias", "h.10.ln_1.weight", "h.10.ln_1.bias", "h.10.attn.bias", "h.10.attn.masked_bias", "h.10.attn.c_attn.weight", "h.10.attn.c_attn.bias", "h.10.attn.c_proj.weight", "h.10.attn.c_proj.bias", "h.10.ln_2.weight", "h.10.ln_2.bias", "h.10.mlp.c_fc.weight", "h.10.mlp.c_fc.bias", "h.10.mlp.c_proj.weight", "h.10.mlp.c_proj.bias", "h.11.ln_1.weight", "h.11.ln_1.bias", "h.11.attn.bias", "h.11.attn.masked_bias", "h.11.attn.c_attn.weight", "h.11.attn.c_attn.bias", "h.11.attn.c_proj.weight", "h.11.attn.c_proj.bias", "h.11.ln_2.weight", "h.11.ln_2.bias", "h.11.mlp.c_fc.weight", "h.11.mlp.c_fc.bias", "h.11.mlp.c_proj.weight", "h.11.mlp.c_proj.bias", "ln_f.weight", "ln_f.bias". 
	Unexpected key(s) in state_dict: "_read_in.weight", "_read_in.bias", "_backbone.wte.weight", "_backbone.wpe.weight", "_backbone.h.0.ln_1.weight", "_backbone.h.0.ln_1.bias", "_backbone.h.0.attn.bias", "_backbone.h.0.attn.masked_bias", "_backbone.h.0.attn.c_attn.weight", "_backbone.h.0.attn.c_attn.bias", "_backbone.h.0.attn.c_proj.weight", "_backbone.h.0.attn.c_proj.bias", "_backbone.h.0.ln_2.weight", "_backbone.h.0.ln_2.bias", "_backbone.h.0.mlp.c_fc.weight", "_backbone.h.0.mlp.c_fc.bias", "_backbone.h.0.mlp.c_proj.weight", "_backbone.h.0.mlp.c_proj.bias", "_backbone.h.1.ln_1.weight", "_backbone.h.1.ln_1.bias", "_backbone.h.1.attn.bias", "_backbone.h.1.attn.masked_bias", "_backbone.h.1.attn.c_attn.weight", "_backbone.h.1.attn.c_attn.bias", "_backbone.h.1.attn.c_proj.weight", "_backbone.h.1.attn.c_proj.bias", "_backbone.h.1.ln_2.weight", "_backbone.h.1.ln_2.bias", "_backbone.h.1.mlp.c_fc.weight", "_backbone.h.1.mlp.c_fc.bias", "_backbone.h.1.mlp.c_proj.weight", "_backbone.h.1.mlp.c_proj.bias", "_backbone.h.2.ln_1.weight", "_backbone.h.2.ln_1.bias", "_backbone.h.2.attn.bias", "_backbone.h.2.attn.masked_bias", "_backbone.h.2.attn.c_attn.weight", "_backbone.h.2.attn.c_attn.bias", "_backbone.h.2.attn.c_proj.weight", "_backbone.h.2.attn.c_proj.bias", "_backbone.h.2.ln_2.weight", "_backbone.h.2.ln_2.bias", "_backbone.h.2.mlp.c_fc.weight", "_backbone.h.2.mlp.c_fc.bias", "_backbone.h.2.mlp.c_proj.weight", "_backbone.h.2.mlp.c_proj.bias", "_backbone.h.3.ln_1.weight", "_backbone.h.3.ln_1.bias", "_backbone.h.3.attn.bias", "_backbone.h.3.attn.masked_bias", "_backbone.h.3.attn.c_attn.weight", "_backbone.h.3.attn.c_attn.bias", "_backbone.h.3.attn.c_proj.weight", "_backbone.h.3.attn.c_proj.bias", "_backbone.h.3.ln_2.weight", "_backbone.h.3.ln_2.bias", "_backbone.h.3.mlp.c_fc.weight", "_backbone.h.3.mlp.c_fc.bias", "_backbone.h.3.mlp.c_proj.weight", "_backbone.h.3.mlp.c_proj.bias", "_backbone.h.4.ln_1.weight", "_backbone.h.4.ln_1.bias", "_backbone.h.4.attn.bias", "_backbone.h.4.attn.masked_bias", "_backbone.h.4.attn.c_attn.weight", "_backbone.h.4.attn.c_attn.bias", "_backbone.h.4.attn.c_proj.weight", "_backbone.h.4.attn.c_proj.bias", "_backbone.h.4.ln_2.weight", "_backbone.h.4.ln_2.bias", "_backbone.h.4.mlp.c_fc.weight", "_backbone.h.4.mlp.c_fc.bias", "_backbone.h.4.mlp.c_proj.weight", "_backbone.h.4.mlp.c_proj.bias", "_backbone.h.5.ln_1.weight", "_backbone.h.5.ln_1.bias", "_backbone.h.5.attn.bias", "_backbone.h.5.attn.masked_bias", "_backbone.h.5.attn.c_attn.weight", "_backbone.h.5.attn.c_attn.bias", "_backbone.h.5.attn.c_proj.weight", "_backbone.h.5.attn.c_proj.bias", "_backbone.h.5.ln_2.weight", "_backbone.h.5.ln_2.bias", "_backbone.h.5.mlp.c_fc.weight", "_backbone.h.5.mlp.c_fc.bias", "_backbone.h.5.mlp.c_proj.weight", "_backbone.h.5.mlp.c_proj.bias", "_backbone.h.6.ln_1.weight", "_backbone.h.6.ln_1.bias", "_backbone.h.6.attn.bias", "_backbone.h.6.attn.masked_bias", "_backbone.h.6.attn.c_attn.weight", "_backbone.h.6.attn.c_attn.bias", "_backbone.h.6.attn.c_proj.weight", "_backbone.h.6.attn.c_proj.bias", "_backbone.h.6.ln_2.weight", "_backbone.h.6.ln_2.bias", "_backbone.h.6.mlp.c_fc.weight", "_backbone.h.6.mlp.c_fc.bias", "_backbone.h.6.mlp.c_proj.weight", "_backbone.h.6.mlp.c_proj.bias", "_backbone.h.7.ln_1.weight", "_backbone.h.7.ln_1.bias", "_backbone.h.7.attn.bias", "_backbone.h.7.attn.masked_bias", "_backbone.h.7.attn.c_attn.weight", "_backbone.h.7.attn.c_attn.bias", "_backbone.h.7.attn.c_proj.weight", "_backbone.h.7.attn.c_proj.bias", "_backbone.h.7.ln_2.weight", "_backbone.h.7.ln_2.bias", "_backbone.h.7.mlp.c_fc.weight", "_backbone.h.7.mlp.c_fc.bias", "_backbone.h.7.mlp.c_proj.weight", "_backbone.h.7.mlp.c_proj.bias", "_backbone.h.8.ln_1.weight", "_backbone.h.8.ln_1.bias", "_backbone.h.8.attn.bias", "_backbone.h.8.attn.masked_bias", "_backbone.h.8.attn.c_attn.weight", "_backbone.h.8.attn.c_attn.bias", "_backbone.h.8.attn.c_proj.weight", "_backbone.h.8.attn.c_proj.bias", "_backbone.h.8.ln_2.weight", "_backbone.h.8.ln_2.bias", "_backbone.h.8.mlp.c_fc.weight", "_backbone.h.8.mlp.c_fc.bias", "_backbone.h.8.mlp.c_proj.weight", "_backbone.h.8.mlp.c_proj.bias", "_backbone.h.9.ln_1.weight", "_backbone.h.9.ln_1.bias", "_backbone.h.9.attn.bias", "_backbone.h.9.attn.masked_bias", "_backbone.h.9.attn.c_attn.weight", "_backbone.h.9.attn.c_attn.bias", "_backbone.h.9.attn.c_proj.weight", "_backbone.h.9.attn.c_proj.bias", "_backbone.h.9.ln_2.weight", "_backbone.h.9.ln_2.bias", "_backbone.h.9.mlp.c_fc.weight", "_backbone.h.9.mlp.c_fc.bias", "_backbone.h.9.mlp.c_proj.weight", "_backbone.h.9.mlp.c_proj.bias", "_backbone.h.10.ln_1.weight", "_backbone.h.10.ln_1.bias", "_backbone.h.10.attn.bias", "_backbone.h.10.attn.masked_bias", "_backbone.h.10.attn.c_attn.weight", "_backbone.h.10.attn.c_attn.bias", "_backbone.h.10.attn.c_proj.weight", "_backbone.h.10.attn.c_proj.bias", "_backbone.h.10.ln_2.weight", "_backbone.h.10.ln_2.bias", "_backbone.h.10.mlp.c_fc.weight", "_backbone.h.10.mlp.c_fc.bias", "_backbone.h.10.mlp.c_proj.weight", "_backbone.h.10.mlp.c_proj.bias", "_backbone.h.11.ln_1.weight", "_backbone.h.11.ln_1.bias", "_backbone.h.11.attn.bias", "_backbone.h.11.attn.masked_bias", "_backbone.h.11.attn.c_attn.weight", "_backbone.h.11.attn.c_attn.bias", "_backbone.h.11.attn.c_proj.weight", "_backbone.h.11.attn.c_proj.bias", "_backbone.h.11.ln_2.weight", "_backbone.h.11.ln_2.bias", "_backbone.h.11.mlp.c_fc.weight", "_backbone.h.11.mlp.c_fc.bias", "_backbone.h.11.mlp.c_proj.weight", "_backbone.h.11.mlp.c_proj.bias", "_backbone.ln_f.weight", "_backbone.ln_f.bias", "_read_out.weight", "_read_out.bias". 

In [33]:
model_state_dict['model_state_dict'].keys()

odict_keys(['_read_in.weight', '_read_in.bias', '_backbone.wte.weight', '_backbone.wpe.weight', '_backbone.h.0.ln_1.weight', '_backbone.h.0.ln_1.bias', '_backbone.h.0.attn.bias', '_backbone.h.0.attn.masked_bias', '_backbone.h.0.attn.c_attn.weight', '_backbone.h.0.attn.c_attn.bias', '_backbone.h.0.attn.c_proj.weight', '_backbone.h.0.attn.c_proj.bias', '_backbone.h.0.ln_2.weight', '_backbone.h.0.ln_2.bias', '_backbone.h.0.mlp.c_fc.weight', '_backbone.h.0.mlp.c_fc.bias', '_backbone.h.0.mlp.c_proj.weight', '_backbone.h.0.mlp.c_proj.bias', '_backbone.h.1.ln_1.weight', '_backbone.h.1.ln_1.bias', '_backbone.h.1.attn.bias', '_backbone.h.1.attn.masked_bias', '_backbone.h.1.attn.c_attn.weight', '_backbone.h.1.attn.c_attn.bias', '_backbone.h.1.attn.c_proj.weight', '_backbone.h.1.attn.c_proj.bias', '_backbone.h.1.ln_2.weight', '_backbone.h.1.ln_2.bias', '_backbone.h.1.mlp.c_fc.weight', '_backbone.h.1.mlp.c_fc.bias', '_backbone.h.1.mlp.c_proj.weight', '_backbone.h.1.mlp.c_proj.bias', '_backbone.h.2

In [31]:
model.load_state_dict(model_state_dict)

RuntimeError: Error(s) in loading state_dict for GPT2LMHeadModel:
	Missing key(s) in state_dict: "transformer.wte.weight", "transformer.wpe.weight", "transformer.h.0.ln_1.weight", "transformer.h.0.ln_1.bias", "transformer.h.0.attn.bias", "transformer.h.0.attn.masked_bias", "transformer.h.0.attn.c_attn.weight", "transformer.h.0.attn.c_attn.bias", "transformer.h.0.attn.c_proj.weight", "transformer.h.0.attn.c_proj.bias", "transformer.h.0.ln_2.weight", "transformer.h.0.ln_2.bias", "transformer.h.0.mlp.c_fc.weight", "transformer.h.0.mlp.c_fc.bias", "transformer.h.0.mlp.c_proj.weight", "transformer.h.0.mlp.c_proj.bias", "transformer.h.1.ln_1.weight", "transformer.h.1.ln_1.bias", "transformer.h.1.attn.bias", "transformer.h.1.attn.masked_bias", "transformer.h.1.attn.c_attn.weight", "transformer.h.1.attn.c_attn.bias", "transformer.h.1.attn.c_proj.weight", "transformer.h.1.attn.c_proj.bias", "transformer.h.1.ln_2.weight", "transformer.h.1.ln_2.bias", "transformer.h.1.mlp.c_fc.weight", "transformer.h.1.mlp.c_fc.bias", "transformer.h.1.mlp.c_proj.weight", "transformer.h.1.mlp.c_proj.bias", "transformer.h.2.ln_1.weight", "transformer.h.2.ln_1.bias", "transformer.h.2.attn.bias", "transformer.h.2.attn.masked_bias", "transformer.h.2.attn.c_attn.weight", "transformer.h.2.attn.c_attn.bias", "transformer.h.2.attn.c_proj.weight", "transformer.h.2.attn.c_proj.bias", "transformer.h.2.ln_2.weight", "transformer.h.2.ln_2.bias", "transformer.h.2.mlp.c_fc.weight", "transformer.h.2.mlp.c_fc.bias", "transformer.h.2.mlp.c_proj.weight", "transformer.h.2.mlp.c_proj.bias", "transformer.h.3.ln_1.weight", "transformer.h.3.ln_1.bias", "transformer.h.3.attn.bias", "transformer.h.3.attn.masked_bias", "transformer.h.3.attn.c_attn.weight", "transformer.h.3.attn.c_attn.bias", "transformer.h.3.attn.c_proj.weight", "transformer.h.3.attn.c_proj.bias", "transformer.h.3.ln_2.weight", "transformer.h.3.ln_2.bias", "transformer.h.3.mlp.c_fc.weight", "transformer.h.3.mlp.c_fc.bias", "transformer.h.3.mlp.c_proj.weight", "transformer.h.3.mlp.c_proj.bias", "transformer.h.4.ln_1.weight", "transformer.h.4.ln_1.bias", "transformer.h.4.attn.bias", "transformer.h.4.attn.masked_bias", "transformer.h.4.attn.c_attn.weight", "transformer.h.4.attn.c_attn.bias", "transformer.h.4.attn.c_proj.weight", "transformer.h.4.attn.c_proj.bias", "transformer.h.4.ln_2.weight", "transformer.h.4.ln_2.bias", "transformer.h.4.mlp.c_fc.weight", "transformer.h.4.mlp.c_fc.bias", "transformer.h.4.mlp.c_proj.weight", "transformer.h.4.mlp.c_proj.bias", "transformer.h.5.ln_1.weight", "transformer.h.5.ln_1.bias", "transformer.h.5.attn.bias", "transformer.h.5.attn.masked_bias", "transformer.h.5.attn.c_attn.weight", "transformer.h.5.attn.c_attn.bias", "transformer.h.5.attn.c_proj.weight", "transformer.h.5.attn.c_proj.bias", "transformer.h.5.ln_2.weight", "transformer.h.5.ln_2.bias", "transformer.h.5.mlp.c_fc.weight", "transformer.h.5.mlp.c_fc.bias", "transformer.h.5.mlp.c_proj.weight", "transformer.h.5.mlp.c_proj.bias", "transformer.h.6.ln_1.weight", "transformer.h.6.ln_1.bias", "transformer.h.6.attn.bias", "transformer.h.6.attn.masked_bias", "transformer.h.6.attn.c_attn.weight", "transformer.h.6.attn.c_attn.bias", "transformer.h.6.attn.c_proj.weight", "transformer.h.6.attn.c_proj.bias", "transformer.h.6.ln_2.weight", "transformer.h.6.ln_2.bias", "transformer.h.6.mlp.c_fc.weight", "transformer.h.6.mlp.c_fc.bias", "transformer.h.6.mlp.c_proj.weight", "transformer.h.6.mlp.c_proj.bias", "transformer.h.7.ln_1.weight", "transformer.h.7.ln_1.bias", "transformer.h.7.attn.bias", "transformer.h.7.attn.masked_bias", "transformer.h.7.attn.c_attn.weight", "transformer.h.7.attn.c_attn.bias", "transformer.h.7.attn.c_proj.weight", "transformer.h.7.attn.c_proj.bias", "transformer.h.7.ln_2.weight", "transformer.h.7.ln_2.bias", "transformer.h.7.mlp.c_fc.weight", "transformer.h.7.mlp.c_fc.bias", "transformer.h.7.mlp.c_proj.weight", "transformer.h.7.mlp.c_proj.bias", "transformer.h.8.ln_1.weight", "transformer.h.8.ln_1.bias", "transformer.h.8.attn.bias", "transformer.h.8.attn.masked_bias", "transformer.h.8.attn.c_attn.weight", "transformer.h.8.attn.c_attn.bias", "transformer.h.8.attn.c_proj.weight", "transformer.h.8.attn.c_proj.bias", "transformer.h.8.ln_2.weight", "transformer.h.8.ln_2.bias", "transformer.h.8.mlp.c_fc.weight", "transformer.h.8.mlp.c_fc.bias", "transformer.h.8.mlp.c_proj.weight", "transformer.h.8.mlp.c_proj.bias", "transformer.h.9.ln_1.weight", "transformer.h.9.ln_1.bias", "transformer.h.9.attn.bias", "transformer.h.9.attn.masked_bias", "transformer.h.9.attn.c_attn.weight", "transformer.h.9.attn.c_attn.bias", "transformer.h.9.attn.c_proj.weight", "transformer.h.9.attn.c_proj.bias", "transformer.h.9.ln_2.weight", "transformer.h.9.ln_2.bias", "transformer.h.9.mlp.c_fc.weight", "transformer.h.9.mlp.c_fc.bias", "transformer.h.9.mlp.c_proj.weight", "transformer.h.9.mlp.c_proj.bias", "transformer.h.10.ln_1.weight", "transformer.h.10.ln_1.bias", "transformer.h.10.attn.bias", "transformer.h.10.attn.masked_bias", "transformer.h.10.attn.c_attn.weight", "transformer.h.10.attn.c_attn.bias", "transformer.h.10.attn.c_proj.weight", "transformer.h.10.attn.c_proj.bias", "transformer.h.10.ln_2.weight", "transformer.h.10.ln_2.bias", "transformer.h.10.mlp.c_fc.weight", "transformer.h.10.mlp.c_fc.bias", "transformer.h.10.mlp.c_proj.weight", "transformer.h.10.mlp.c_proj.bias", "transformer.h.11.ln_1.weight", "transformer.h.11.ln_1.bias", "transformer.h.11.attn.bias", "transformer.h.11.attn.masked_bias", "transformer.h.11.attn.c_attn.weight", "transformer.h.11.attn.c_attn.bias", "transformer.h.11.attn.c_proj.weight", "transformer.h.11.attn.c_proj.bias", "transformer.h.11.ln_2.weight", "transformer.h.11.ln_2.bias", "transformer.h.11.mlp.c_fc.weight", "transformer.h.11.mlp.c_fc.bias", "transformer.h.11.mlp.c_proj.weight", "transformer.h.11.mlp.c_proj.bias", "transformer.ln_f.weight", "transformer.ln_f.bias", "lm_head.weight". 
	Unexpected key(s) in state_dict: "model_state_dict", "optimizer_state_dict", "train_step". 

In [22]:
import torch

model_path = "./models/linear_regression/pretrained/state.pt"
config_path = "./models/linear_regression/pretrained/config.yaml"
model_state_dict = torch.load(model_path, map_location=torch.device('cpu'))

config = AutoConfig.from_pretrained(config_path)
# model = GPT2LMHeadModel(config)
# model.load_state_dict(model_state_dict)

OSError: It looks like the config file at './models/linear_regression/pretrained/config.yaml' is not a valid JSON file.

In [7]:


model_state_dict = torch.load(model_path, map_location=torch.device('cpu'))

In [14]:
AutoModel.from_pretrained(pretrained_model_name_or_path="GPT2", state_dict=model_state_dict['model_state_dict'])

OSError: We couldn't connect to 'https://huggingface.co/' to load this model and it looks like None is not the path to a directory conaining a config.json file.
Checkout your internet connection or see how to run the library in offline mode at 'https://huggingface.co/docs/transformers/installation#offline-mode'.

In [ ]:
model_state_dict['model_state_dict']

OrderedDict([('_read_in.weight',
              tensor([[-4.1718e-04, -3.3895e-01,  4.0805e-01,  ..., -1.1323e-01,
                       -7.3371e-03,  4.2963e-01],
                      [-2.9153e-02, -2.3397e-01,  2.3059e-01,  ...,  2.9892e-01,
                       -4.6796e-01,  1.9676e-01],
                      [ 2.0871e-01, -3.2949e-01,  1.8568e-01,  ..., -2.8788e-01,
                        1.9067e-01, -2.4425e-02],
                      ...,
                      [ 3.6407e-02,  1.0427e-01,  2.1405e-02,  ..., -3.3273e-01,
                       -1.9290e-01,  1.9545e-01],
                      [ 1.1240e-01, -5.8714e-02,  6.3293e-02,  ..., -1.4581e-01,
                       -1.7252e-01, -1.5185e-01],
                      [ 2.5849e-02, -2.0403e-02, -3.6269e-02,  ...,  1.9423e-01,
                       -3.4288e-01, -1.7775e-01]])),
             ('_read_in.bias',
              tensor([ 9.9162e-02, -4.2385e-01,  2.0162e-01,  1.6045e-01, -1.2797e+00,
                       1.5664e-01

In [1]:
import transformers

In [3]:
from transformers import AutoModel

model = AutoModel.from_pretrained(model_path)

OSError: It looks like the config file at './models/linear_regression/pretrained/state.pt' is not a valid JSON file.

In [1]:
import numpy as np
import statistics
from sklearn.linear_model import LinearRegression

In [2]:
d= 20

In [4]:
## Reproduce linear regression
def compute_nonskewed_samples_linreg(n, samples=100):
    X = np.random.normal(size=(n,d))
    w = np.random.normal(size=(d))

    y = X @ w
    w_pred = np.linalg.lstsq(X,y)[0]
    
    new_x = np.random.normal(size=(samples,d))
    return np.mean((new_x @ w - new_x @ w_pred)**2/d)

In [5]:
def trials_nonskewed_compute_samples_linreg(n,trials=1000):
    s = 0
    for _ in range(trials):
        s += compute_nonskewed_samples_linreg(n)
    return s/trials

In [8]:
trials_nonskewed_compute_samples_linreg(15)

/var/folders/q2/v9j0v5657_z14pfkvj6z6flw0000gn/T/ipykernel_10440/2055469217.py:7: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  w_pred = np.linalg.lstsq(X,y)[0]


0.24935913383864136

In [44]:
n=5

In [46]:
X = np.random.normal(size=(n,d))
w = np.random.normal(size=(d))

y = X @ w
w_pred = np.array([np.linalg.lstsq(X[:,i:(i+1)],y)[0] for i in range(d)])

new_x = np.random.normal(size=(1,d))


/var/folders/q2/v9j0v5657_z14pfkvj6z6flw0000gn/T/ipykernel_10440/3537805443.py:5: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  w_pred = np.array([np.linalg.lstsq(X[:,i:(i+1)],y)[0] for i in range(d)])


In [47]:
(new_x @ w - new_x @ w_pred)**2/d

array([[0.1129271]])

In [48]:
new_x @ w - new_x @ w_pred

array([[-1.50284466]])

In [9]:
## Univariate linear regression
def compute_nonskewed_samples_univariate(n, samples=100):
    X = np.random.normal(size=(n,d))
    w = np.random.normal(size=(d))
    
    y = X @ w
    w_pred = np.array([np.linalg.lstsq(X[:,i:(i+1)],y)[0] for i in range(d)])
    
    new_x = np.random.normal(size=(samples,d))
    return np.mean((new_x @ w - new_x @ w_pred)**2/d)

def trials_nonskewed_compute_samples_univariate(n,trials=1000):
    s = 0
    for _ in range(trials):
        s += compute_nonskewed_samples_linreg(n)
    return s/trials

In [12]:
trials_nonskewed_compute_samples_univariate(15,trials=1000)

/var/folders/q2/v9j0v5657_z14pfkvj6z6flw0000gn/T/ipykernel_10440/2055469217.py:7: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  w_pred = np.linalg.lstsq(X,y)[0]


0.24447865131453775

In [54]:
def generate_random_cov(d):
    import scipy.linalg as la
    des = np.random.rand(d) * np.array([1/i**2 for i in range(1,d+1)])

    s = np.diag(des)
    q, _ = la.qr(np.random.rand(d, d))
    semidef = q.T @ s @ q
    return semidef

In [60]:
## Reproduce linear regression
def compute_skewed_samples_linreg(n, samples=1000):

    cov = generate_random_cov(d)
    X = np.random.multivariate_normal(np.zeros(d), cov, size=(n))
    w = np.random.normal(size=(d))

    y = X @ w
    w_pred = np.linalg.lstsq(X,y)[0]
    
    new_x = np.random.multivariate_normal(np.zeros(d), cov, size=(samples))
    print(len((new_x @ w - new_x @ w_pred)**2/d))
    return np.mean((new_x @ w - new_x @ w_pred)**2/d)

def trials_skewed_compute_samples_linreg(n,trials=10):
    s = 0
    for _ in range(trials):
        s += compute_skewed_samples_linreg(n)
    return s/trials

In [61]:
trials_skewed_compute_samples_linreg(5)

1000
1000
1000
1000
1000
1000
1000
1000
1000
1000


/var/folders/q2/v9j0v5657_z14pfkvj6z6flw0000gn/T/ipykernel_10440/3812004266.py:9: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  w_pred = np.linalg.lstsq(X,y)[0]


0.008613774433401169

In [56]:
n=5

In [32]:
cov = generate_random_cov(d)

[0.19957347 0.12370521 0.096889   0.0022147  0.00389768 0.01999154
 0.0104042  0.00053727 0.00835697 0.00783478 0.00734637 0.00062493
 0.00339866 0.00059259 0.00055691 0.00186931 0.00151627 0.00149367
 0.00084837 0.00243365]


In [33]:
X = np.random.multivariate_normal(np.zeros(d), cov, size=(n))
w = np.random.normal(size=(d))

In [34]:
y = X @ w
w_pred = np.linalg.lstsq(X,y)[0]

/var/folders/q2/v9j0v5657_z14pfkvj6z6flw0000gn/T/ipykernel_10440/1099328868.py:2: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  w_pred = np.linalg.lstsq(X,y)[0]


In [35]:
w_pred

array([ 0.09557142,  0.34528549, -0.33948364,  0.50286773,  0.42067673,
        0.45575995, -0.2609076 , -0.00695674, -0.14402256, -0.15646493,
        0.02931849, -0.95661399,  0.81629993, -0.03400288, -0.6813568 ,
        0.18671029, -0.09559731,  0.57286524,  0.95783502,  0.77709824])

In [36]:
w

array([-0.64502314,  0.98613042, -0.76276744,  2.0554591 ,  1.71257606,
        0.78563448,  0.8357523 ,  0.64581556,  0.4071628 ,  0.20123786,
       -0.91574574, -1.50694569,  1.15091709,  0.12633244, -0.53158905,
       -0.5294817 ,  0.36699982,  0.23003489,  0.29964033, -0.51276991])

In [37]:
new_x = np.random.multivariate_normal(np.zeros(d), cov, size=(1))

In [39]:
new_x @ w_pred

array([0.46801116])

In [40]:
new_x @ w

array([-0.01841874])

In [43]:
(new_x @ w - new_x @ w_pred)**2/d

array([0.0118307])

In [18]:
## Univariate linear regression
def compute_skewed_samples_univariate(n, samples=100):
    cov = generate_random_cov(d)
    X = np.random.multivariate_normal(np.zeros(d), cov, size=(n))
    w = np.random.normal(size=(d))
    
    y = X @ w
    w_pred = np.array([np.linalg.lstsq(X[:,i:(i+1)],y)[0] for i in range(d)])
    
    new_x = np.random.multivariate_normal(np.zeros(d), cov, size=(samples))
    return np.mean((new_x @ w - new_x @ w_pred)**2/d)

def trials_skewed_compute_samples_univariate(n,trials=100):
    s = 0
    for _ in range(trials):
        s += compute_nonskewed_samples_univariate(n)
    return s/trials

In [22]:
trials_skewed_compute_samples_univariate(10)

/var/folders/q2/v9j0v5657_z14pfkvj6z6flw0000gn/T/ipykernel_10440/1072340752.py:7: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  w_pred = np.array([np.linalg.lstsq(X[:,i:(i+1)],y)[0] for i in range(d)])


3.8780201583850005

In [4]:
## Data generation process
new_basis = np.random.rand(d,d)
assert np.linalg.det(new_basis) != 0

eigenvalues = np.diag(np.random.rand(d) * np.array([1/i**2 for i in range(1,d+1)]))
cov = new_basis @ eigenvalues @ new_basis.T


In [9]:
other = []
for _ in range(10000):
    X = np.random.normal(size=(10,d))#np.random.multivariate_normal(np.zeros(d), cov, size=(10))
    w = np.random.normal(size=(d))

    y = X @ w
    w_pred = np.linalg.inv(X.T @ X) @ X.T @ y

    other.append(np.mean((new_x @ w - new_x @ w_pred)**2/d))
np.mean(other)

LinAlgError: Singular matrix

In [69]:
Linew_x = np.random.normal(size=(100,d))


0.7638859441564224

In [58]:
## Data
X = np.random.multivariate_normal(np.zeros(d), cov, size=(10))
w = np.random.normal(size=(d))

y = X @ w
correctmodel = LinearRegression()
correctmodel.fit(X,y)


## Univariate model
newmodel = [None for _ in range(d)]
for xcoord in range(d):
    newmodel[xcoord] = LinearRegression()
    newmodel[xcoord].fit(X[:,xcoord].reshape(-1, 1),y)


## New data
tally = []
other = []
for _ in range(1000):
    new_x = np.random.multivariate_normal(np.zeros(d), cov, size=(1))

    ## Other way
    s = 0 
    for xcoord in range(d):
        s += newmodel[xcoord].predict([new_x[:,xcoord]])
    tally.append((new_x @ w-s)**2/d)
    other.append((new_x @ w - correctmodel.predict(new_x))**2/d)
print(statistics.median(tally))

[18.34405811]


In [59]:
np.mean(other)

0.0012507962138239316

In [ ]:
    new_basis = np.random.rand(d,d)
    assert np.linalg.det(new_basis) != 0

    eigenvalues = np.diag(np.random.rand(d) * np.array([1/i**2 for i in range(1,d+1)]))
    cov = new_basis @ eigenvalues @ new_basis.T


In [54]:
print(statistics.mean(other))

TypeError: can't convert type 'ndarray' to numerator/denominator

In [ ]:
Li

In [9]:
newmodel = LinearRegression()
newmodel.fit(X[:,0].reshape(-1, 1),y)

LinearRegression()

array([-0.93505332])

In [151]:
L[0].coef_

array([-0.73050409])

In [152]:
w

array([-1.30027051,  0.10755878, -1.65512584,  0.53695437, -0.09525121,
        1.34808472, -1.14959473,  0.70632195, -0.13916849,  1.42335692,
        0.02233433, -1.26107679,  0.3373724 , -0.31038984, -1.87526967,
       -0.40671239,  1.74483858, -1.20441002,  2.00420493,  1.471041  ])

In [96]:
new_x = np.random.multivariate_normal(np.zeros(d), cov, size=(1,))

In [101]:
model.predict(new_x)

array([-0.19220312])

In [102]:
new_x @ w

array([-0.19220312])

In [15]:
def generate_dataset(d):
    new_basis = np.random.rand(d,d)
    assert np.linalg.det(new_basis) != 0